# Generated by Django 4.0.2 on 2022-02-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='direction',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_name_ru',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_name_ua',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='equipment',
            name='jsname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
