# Generated by Django 4.0.2 on 2022-02-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0002_remove_equipment_equipment_name_equipment_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='jsname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
