# Generated by Django 4.0.2 on 2022-02-23 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0005_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='calc_api.direction'),
        ),
    ]
