# Generated by Django 4.0.2 on 2022-03-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0006_alter_equipment_direction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('jsname', 'vendor_id'), name='unique_jsname'),
        ),
    ]
