# Generated by Django 4.0.2 on 2022-03-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0007_equipment_unique_jsname'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='direction',
            constraint=models.UniqueConstraint(fields=('direction',), name='unique_direction'),
        ),
    ]
