# Generated by Django 4.0.2 on 2022-04-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0012_alter_phone_customer_alter_phone_stuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_supervisor', to='calc_api.stage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_supervisor', to='calc_api.staff'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('first_name', 'second_name', 'email'), name='unique_customer'),
        ),
        migrations.AddConstraint(
            model_name='phone',
            constraint=models.UniqueConstraint(fields=('phone',), name='unique_phone'),
        ),
    ]
