# Generated by Django 4.0.2 on 2022-04-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0013_alter_project_stage_alter_project_supervisor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='ProjectFiles',
        ),
    ]
