# Generated by Django 4.0.2 on 2022-04-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0014_rename_file_projectfiles'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer',
        ),
        migrations.RemoveConstraint(
            model_name='phone',
            name='unique_phone',
        ),
    ]
