# Generated by Django 4.0.2 on 2022-04-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0015_remove_customer_unique_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfiles',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_project', to='calc_api.project'),
            preserve_default=False,
        ),
    ]
