# Generated by Django 4.0.2 on 2022-04-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0016_projectfiles_project_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('first_name', 'second_name', 'email'), name='unique_customer'),
        ),
        migrations.AddConstraint(
            model_name='phone',
            constraint=models.UniqueConstraint(fields=('phone',), name='unique_phone'),
        ),
    ]
