# Generated by Django 4.0.2 on 2022-04-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0018_alter_phone_phone_alter_staff_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='second_name',
            field=models.CharField(max_length=20),
        ),
    ]
